version: '3.9'

services:
  frontend:
    image: woudan/example-frontend
    build: .
    ports:
      - '5001:5000'

  backend:
    image: woudan/example-backend
    build: .
    environment:
      REDIS_HOST: 'redis'
    ports:
      - '8080:8080'

  redis:
    image: redis
    build: .