version: '3.9'

services:
  app:
    image: woudan/express_app
    ports:
      - '8080:8080'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true # only allowed to update containers with the enabled label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower